### ISSUE TITLE
File for Edit User and Logout is Missing

### ISSUE THREAD

**Issue by Mohuz** [siamon123/warehouse-inventory-system#1]
I have downloaded the source codes and so far I found out that the file for edit user and logout are missing.

**Comment by siamon123** [comment]
I did upload logout.php but by mistake i didn’t like the file in header.php and i added edit_user file. Thank you for let me know.

**Comment by Mohuz** [comment]
Thanks sir, I see the file added now. Keep it up.

**Comment by siamon123** [comment]
No problem sir.
