### ISSUE TITLE
Parameter in addsale.php 

### ISSUE THREAD

**Issue by gian123** [siamon123/warehouse-inventory-system#13]
Hi 

In the file add_sale.php I can see  this lines
`<div class="row">
  <div class="col-md-6">
    <?php echo display_msg($msg); ?>
    <form method="post" action="ajax.php" autocomplete="off" id="sug-form">
        <div class="form-group">
          <div class="input-group">
            <span class="input-group-btn">
              <button type="submit" class="btn btn-primary">Buscar</button>
            </span>
            <input type="text" id="sug_input" class="form-control" name="title"  placeholder="Producto">
         </div>
         <div id="result" class="list-group"></div>
        </div>
    </form>
  </div>
</div>`

and I can see you send a parameter to ajax.php 

`<?php
 // Auto suggetion
    $html = '';
   if(isset($_POST['product_name']) && strlen($_POST['product_name']))
   {
     $products = find_product_by_title($_POST['product_name']);
     if($products){
        foreach ($products as $product):
           $html .= "<li class=\"list-group-item\">";
           $html .= $product['name'];
           $html .= "</li>";
         endforeach;
      } else {

        $html .= '<li onClick=\"fill(\''.addslashes().'\')\" class=\"list-group-item\">';
        $html .= 'No encontrado';
        $html .= "</li>";

      }

      echo json_encode($html);
   }
 ?>`

the problem is I want to change the parameter but I dont see the pamarameter called "product_name" from add_sale.php to ajax.php..can you explain me pleasee. I need this project for my school..=)

Wich is your logic, please let me know .

Is really interested your system.

Thanks

**Comment by siamon123** [comment]
This function located in includes/sql.php

  /*--------------------------------------------------------------*/
  /* Function for Finding all product name
  /* Request coming from ajax.php for auto suggest
  /*--------------------------------------------------------------*/
   function find_product_by_title($product_name){
     global $db;
     $p_name = remove_junk($db->escape($product_name));
     $sql = "SELECT name FROM products WHERE name like '%$p_name%' LIMIT 5";
     $result = find_by_sql($sql);
     return $result;
   }

**Comment by gian123** [comment]
Hi bro thank for your atenttion , I understant the fuction of the method
called " find_product_by_title" but  my dude is about how  the file
 add_sale.php  sends the parameter  $_POST['product_name'] to ajax.php int
the next form  the parameter "product_name" doesn't exist. but this form
send ti ajax.php this parameter. I will put in red.


*    <form method="post" action="ajax.php" autocomplete="off"
id="sug-form">*

*        <div class="form-group">*

*          <div class="input-group">*

*            <span class="input-group-btn">*

*              <button type="submit" class="btn
btn-primary">Buscar</button>*

*            </span>*

*            <input type="text" id="sug_input" class="form-control"
name="title"  placeholder="Buscar por nombre de producto">*

*         </div>*

*         <div id="result" class="list-group"></div>*

*        </div>*

*    </form>*

*  </div>*

*</div>*




*<?php*

* // Auto suggetion*

*    $html = '';*

*   if(isset($_POST['product_name']) && strlen($_POST['product_name']))*

*   {*

*     $products = find_product_by_title($_POST['product_name']);*

*     if($products){*

*        foreach ($products as $product):*

*           $html .= "<li class=\"list-group-item\">";*

*           $html .= $product['name'];*

*           $html .= "</li>";*

*         endforeach;*

*      } else {*


*        $html .= '<li onClick=\"fill(\''.addslashes().'\')\"
class=\"list-group-item\">';*

*        $html .= 'No encontrado';*

*        $html .= "</li>";*


*      }*


Help me please,


Thank.

2016-06-07 15:36 GMT-05:00 Siamon Hasan <notifications@github.com>:

**Comment by siamon123** [comment]
i'm retrieving  data by jQuery, check out function.js  file.

**Comment by gian123** [comment]
Ok I understand, Thanks very much =)

2016-06-07 21:11 GMT-05:00 Siamon Hasan <notifications@github.com>:

**Comment by siamon123** [comment]
No problem!

**Comment by gian123** [comment]
Hi , the really I staying many hours in this example because I need to
present this in my school this last week and please I need your help onlly
in this part becase I start to develop recently and I dont know javascript
in hight level.I need the next image in your source code.

[image: Imágenes integradas 1]



please help me only with this..

Thank you for your attention

Really thank you very much.

2016-06-07 23:12 GMT-05:00 Siamon Hasan <notifications@github.com>:

**Comment by gian123** [comment]
Can you help me bro?..I need know if you can help me.

Thanks

2016-06-08 0:41 GMT-05:00 jeanfranco gutierrez <
gianfrancogutierrez12@gmail.com>:

**Comment by siamon123** [comment]
Sure.

Siamon Hasan

**Comment by siamon123** [comment]
you mean this code

```
`function suggetion() {

     $('#sug_input').keyup(function(e) {

         var formData = {
             'product_name' : $('input[name=title]').val()
         };

         if(formData['product_name'].length >= 1){

           // process the form
           $.ajax({
               type        : 'POST',
               url         : 'ajax.php',
               data        : formData,
               dataType    : 'son',

               encode      : true
           })
               .done(function(data) {
                   //console.log(data);
                   $('#result').html(data).fadeIn();
                   $('#result li').click(function() {

                     $('#sug_input').val($(this).text());
                     $('#result').fadeOut(500);

                   });

                   $("#sug_input").blur(function(){
                     $("#result").fadeOut(500);
                   });

               });

         } else {

           $("#result").hide();

         };

         e.preventDefault();
     });

 }`
```

**Comment by gian123** [comment]
Closet en tu culo

2016-10-13 12:48 GMT-05:00 Siamon Hasan <notifications@github.com>:
