### ISSUE TITLE
timezone issue

### ISSUE THREAD

**Issue by SampadR** [siamon123/warehouse-inventory-system#14]
Getting the error of , it is not good to depend on system time. Can you please help us where to set the time and change UTC to IST and fix the issue.

**Comment by Syedwaheed** [comment]
You can change time to your time zone just like below.
`<div class="header-date pull-left">
        <strong><?php date_default_timezone_set("Asia/Karachi");echo (new \DateTime())->format('F d Y h:i:sa');?></strong>
      </div>`
