### ISSUE TITLE
add sale

### ISSUE THREAD

**Issue by ivandgreat** [siamon123/warehouse-inventory-system#16]
This is a nice product u created.

When click the Add Sale, nothing happens.

Thanks.

**Comment by siamon123** [comment]
you have to search for a product name.

**Comment by ivandgreat** [comment]
![image](https://cloud.githubusercontent.com/assets/5754562/19362331/0d8ba464-918f-11e6-8937-af980200474a.png)

I already search a product, but still nothing changes. Please see image.

**Comment by siamon123** [comment]
you have any product name register in database?

**Comment by ivandgreat** [comment]
![image](https://cloud.githubusercontent.com/assets/5754562/19376068/36cba726-91e3-11e6-94f1-bb26c4c70475.png)



I have a product already. I manually added a sales on the mysql. But still nothing happens when press Add Sales Button.

**Comment by siamon123** [comment]
put your  product name into product search field.

**Comment by ivandgreat** [comment]
I already did on my first post. 

please correct me if i'm wrong, is there's missing code here from add_sale.php? it seems the data wheren't called to update the table.

> <div class="panel-body">
        <form method="post" action="add_sale.php">
         <table class="table table-bordered">
           <thead>
            <th> Item </th>
            <th> Price </th>
            <th> Qty </th>
            <th> Total </th>
            <th> Date</th>
            <th> Action</th>
           </thead>
             <tbody  id="product_info"> </tbody>

>

**Comment by siamon123** [comment]
for me it's seen like functions.js file not loding.

**Comment by ivandgreat** [comment]
any advice how to fix this. Thanks.

**Comment by siamon123** [comment]
look at this line in footer.php file 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
somehow it's not loading to your server. just download jQuery library include in footer.php file.

**Comment by ivandgreat** [comment]
i have checked the footer.php, and i have that src.

the add sale.php code doesn't include the data for <td></td> to be inserted, its' only have the <th></th> from the code.

**Comment by dalt0ny** [comment]
Hi ivandgreat, could you fix this issue?
