### ISSUE TITLE
Reports Not working

### ISSUE THREAD

**Issue by yayatimsa** [siamon123/warehouse-inventory-system#2]
Your warehouse invetory system is cool. but part of the report is still error. hehe. approximately in the section where the error?

**Comment by siamon123** [comment]
What type error you getting?

**Comment by yayatimsa** [comment]
No response. No error message. But does not display any. Only white screen 

Dari:"Siamon Hasan" <notifications@github.com>
Tanggal:Rab, 8 Jul 2015 pada 6:38
Judul:Re: [warehouse-inventory-system] Reports Not working (#2)

What type error you getting?

**Comment by siamon123** [comment]
i think you have old copy try to install a new copy. i updated  week ago.
