### ISSUE TITLE
Ajax.php is not working

### ISSUE THREAD

**Issue by exoticmankey** [siamon123/warehouse-inventory-system#3]
When you click the find it button at sale -> add sale -> find it, ajax.php does not seem to respond or display the result. I typed ipad. It didn't show anything.

**Comment by siamon123** [comment]
Check you have any product name in database or not.

**Comment by exoticmankey** [comment]
According to your inventory sql https://github.com/siamon123/warehouse-inventory-system/blob/master/inventory.sql you don't have. But if there were any product name, where should it be placed?

**Comment by siamon123** [comment]
yea it's should be there and product manage section too. are you using internet explorer?

**Comment by exoticmankey** [comment]
For Product manage:
Product manage section is not present at inventory.sql . I could not find. I still cannot understand what you mean. 

For Internet explorer:
I am running the php website in chrome and safari. Would there be any problem with those browsers?

Is the ajax.php working fine on your side? Everything else works on your project except this part. Hope we can continue helping each other thanks.

**Comment by siamon123** [comment]
if you login in then look at left sidebar you will find it. no browser not issue for you. i instilled  new copy its work great for me. why not try to install fresh copy?

**Comment by exoticmankey** [comment]
Sale I see yes it is working. I click from the left side of the browser. But when I click add sale inside sale screen and input the item i want to find. I click find and there will be no result. After clicking find it button it will go to ajax.php which doesn't show any result. I will try to re-run the entire project as you advised see how it goes if the problem is still there.

**Comment by siamon123** [comment]
ok, is auto suggestion work for you?

**Comment by exoticmankey** [comment]
Negative. I don't see any suggestions whenever I type something. Does it have that feature?

**Comment by siamon123** [comment]
yea i have that feature. Somehow functions.js not working for you.

**Comment by exoticmankey** [comment]
Yes I believe so. I saw product name already at functions.js but where is this functions.js referenced? 

Does it also have something to do with what browser am i using for the js file not to work?

**Comment by exoticmankey** [comment]
Yes this is exactly what is happening. Js doesn't seem to work. what web browser are you using my friend?

**Comment by siamon123** [comment]
functions.js referenced in footer.php file. my default browser is safari.

**Comment by exoticmankey** [comment]
Will check it out. This java scripts can it be re-located at the header and not at the footer?

**Comment by exoticmankey** [comment]
I got it working. But only the date pickers. I'm still not into the find it button to process the input for add sale. I'll check it out then i'll close this issue once i have fixed both. I have an idea already how to do it. Thanks for the mentioning the locations siamon123. Let you know if i have fixed all already.

**Comment by siamon123** [comment]
just play with it little bit more. you can fix it easily.

**Comment by exoticmankey** [comment]
Siamon I have finally made your entire system work. Thank you for conversating with me. May more luck come into your life. This thread now i close. take care

**Comment by halil-indo** [comment]
haw to add year on products table? i have try to add that, when edit and add product i can do that, but when display products there is Notice: Undefined index: year in C:\xampp\htdocs\inventory\product.php on line 40

**Comment by siamon123** [comment]
I don't have that feature but you can add new filed type datetime in products table.

**Comment by halil-indo** [comment]
thanks siamon123. i have try it, but the table years cannot display on products.

**Comment by siamon123** [comment]
i am adding that feature next version. i am also cleaning up some bugs and adding few more features.

**Comment by halil-indo** [comment]
thanks simon123,  i appreciate that. i will waiting for that

**Comment by exoticmankey** [comment]
siamon123 at your next update I will start the unit testing with you. I am also updating your version of codes in my side of using your work. Thank you very much and may God Allah bless you more!
