### ISSUE TITLE
Setting user previlledges

### ISSUE THREAD

**Issue by rakhitanwar** [siamon123/warehouse-inventory-system#4]
Hi,

Thanks for the great tool, I want to add two users in the application one is admin and second is for entries only who can not add or remove users.

Thanks

**Comment by siamon123** [comment]
you have to write new function for that. if you can wait two more weeks.i will help you out. i am currently working on multi level user management system. Thank you.

**Comment by rakhitanwar** [comment]
Thanks for prompt reply. waiting for solution .
Thanks

**Comment by exoticmankey** [comment]
Ey, this is good topic. I'm camping here.

**Comment by exoticmankey** [comment]
I hope product pictures and user pictures could be added in this system too.

**Comment by siamon123** [comment]
you have to add a new column in user table 

user_level INT(11) NOT NULL

Then put this function in sql.php file 

  /*--------------------------------------------------------------*/
    /*Check User Level
    /*--------------------------------------------------------------*/
   function check_user_level($level)
    {
      global $session;
      $current_user = current_user();
      if($current_user['user_level'] <= (int)$level){
        return $level;
      } else {
        $session->msg("d", "Sorry you don't have permission to view this page.");
        redirect('home.php', false);
      }
    }

now you just have to call the function   check_user_level(1); after checking isUserLoggedIn(true).
Remember  1 is admin  privilege. Hope it's will solve you'r problem.
@exoticmankey i will add it in near feature. 
Thank you!

**Comment by rhonpicache** [comment]
hi, i already got into the login screen. the problem is i cannot sign in. i used the default admin admin. i even created a new user on phpmyadmin. still cannot access. hope you can help me. thanks

**Comment by siamon123** [comment]
Did you put your database info in config.php?

**Comment by rhonpicache** [comment]
yes i did

**Comment by exoticmankey** [comment]
Ey man can you let us know how you figured the thing out? thanks

**Comment by rhonpicache** [comment]
under config.php
<?php
 // Database Constants
  define('DB_SERVER','localhost');
  define('DB_USER','root');
  define('DB_PASS','');
  define('DB_NAME','inventory'); //inventory is my database name

?>

under database.php

<?php
  include_once('config.php');

  $con = mysqli_connect('localhost','root','');

  if(!$con){
    die('<pre> Database Connection Failed '.mysqli_connect_error().'</pre>' );
  } else {
    $select_db = $con->select_db('inventory');
    if(!$select_db){
      die('Sorry failed to select Database');
    }
  }

?>

**Comment by siamon123** [comment]
are you using xampp server?

**Comment by rhonpicache** [comment]
yep

**Comment by siamon123** [comment]
some xampp user include file issue. so i updated database.php, if it's work please let me know and i am sorry for respond you late. Thank you!

**Comment by hidelberto** [comment]
Your "Check User Level" script doesn't run. I'm trying to call check_user_level(1); after checking isUserLoggedIn(true) but doesn't work. Could you check your code if something is missing?

**Comment by siamon123** [comment]
i might missing something, sorry not sure but i next version i am take care of it. i just need little time to finish sales and report section. Thank you.
![screen shot 2015-09-23 at 12 36 28 am](https://cloud.githubusercontent.com/assets/2531819/10038028/2289618c-618c-11e5-8c29-c3f45adb12ce.jpg)

**Comment by hidelberto** [comment]
Thank you. Your inventory system is great!! I will waiting for the next version.

**Comment by exoticmankey** [comment]
Hi Siamon the great creator of this inventory system, how to I see the latest updates you have made with the codes? I mean the one with dates? thank you very much!

**Comment by hidelberto** [comment]
Hi siamon i just found the solution: you must call the function check_user_level(0) instead of (1)

**Comment by siamon123** [comment]
i have plan to update on Sunday Night @exoticmankey ,
i think you missing something, it's should not be 0 @hidelberto.

**Comment by exoticmankey** [comment]
siamon which area should i monitor to find out if you have already updated with the new codes? tq

**Comment by hidelberto** [comment]
Hi siamon, I am wondering when you plan to do the next inventory system update? thanks...

**Comment by siamon123** [comment]
Sorry guys, only categories section didn't change that much  @exoticmankey.
i just push it @hidelberto 
Thank you.

**Comment by exoticmankey** [comment]
@siamon123 I am voluteering to do test unit(s) document from your inventory software. I really like it.

**Comment by siamon123** [comment]
it's will be great @exoticmankey

**Comment by exoticmankey** [comment]
Yes this my return favor to your great app @siam123 the great! harhar

**Comment by SIMONTSAO** [comment]
Hello slamon:
when I run Sales Report --> Sales by dates, I get this message "Parse error: syntax error, unexpected '[' in /home/xxx/sale_report_process.php on line 117" how can I solve the problem ?

**Comment by siamon123** [comment]
i just modify edit_sale And sale_report_process.php files just re-download those two files.
Thank you @SIMONTSAO for Letting me.
